catch invite error and retry
heroku/heroku-orgs pull request #85
Opened 2017-10-10 17:20 UTC by RasPhilCo

Fixes #83

2017-10-11 01:22 UTC, jdxcode commented
Can you add a test?

2017-10-11 01:23 UTC, jdx requested changes

2017-10-11 01:23 UTC, jdxcode commented on commands/members/add.js
> +      yield heroku.request({
Should be await if you’re using async

2017-10-11 17:32 UTC, kahlouie commented
@RasPhilCo @jdxcode Shoot, I just double checked. We don't error on the `inviteMemberToTeam` endpoint if the team doesn't use invitations (Heroku Teams), which means it will just work. I can either add that in, or we can brainstorm another solution. I recommend adding that in since we shouldn't be creating team invitations for Enterprise teams.

2017-10-11 19:27 UTC, RasPhilCo commented
| command (x-axis)/ org type (y) | orgs:add | orgs:set  | 
|---|---|---|
| team w/ invites feature | PUT /teams/:id/invitations | PATCH or PUT /teams/:id/members |  
| team w/o invites feature|  POST or PUT /teams/:id/members |  PATCH or PUT /teams/:id/members |  
| enterprise team  | POST or PUT /teams/:id/members |  PATCH or PUT /teams/:id/members |

2017-10-11 19:29 UTC, RasPhilCo commented
@kahlouie I made a table of api endpoints given org type and command called, does this look right or we missing a command or missing an endpoint or missing a workflow? (If the table is a more distraction than help let me know)

2017-10-11 19:37 UTC, kahlouie commented
@RasPhilCo I edited the table. We should be switching to teams endpoints anyway now. :)

2017-10-11 19:52 UTC, RasPhilCo commented
@kahlouie 👍  will update PR

2017-10-12 23:00 UTC, RasPhilCo commented
@kahlouie 2 things:

1) I added this issue https://github.com/heroku/heroku-orgs/issues/86 to update all the endpoints. The orgs endpoint test mock is shared across all the command tests and updating it here was confusing the point of this PR.
2) Below I've included the test descriptions. I want to make sure we're covering what we think we are covering.

2017-10-12 23:01 UTC, RasPhilCo commented
```
heroku members:add
    without the feature flag team-invite-acceptance
      and group is a team
        ✓ does not warn the user when under the free org limit
        ✓ does not warn the user when over the free org limit
        ✓ does warn the user when at the free org limit
        using --org instead of --team
          ✓ adds the member, but it shows a warning about the usage of -t instead
      and group is an enterprise org
        ✓ adds a member to an org
    with the feature flag team-invite-acceptance
      and group is a team
        ✓ does warn the user when free org limit is caused by invites
        ✓ sends an invite when adding a new user to the team
      and group is an enterprise org
        ✓ sends an invite when adding a new user to the team

  heroku members:set
    and group is a team
      ✓ does not warn the user when under the free org limit
      ✓ does not warn the user when over the free org limit
      ✓ does warn the user when at the free org limit
      using --org instead of --team
        ✓ adds the member, but it shows a warning about the usage of -t instead
    and group is an enterprise org
      ✓ adds a member to an org
```

2017-10-16 19:03 UTC, kahlouie requested changes
In general, it looks good. I wonder if we should change the set to command to only update existing ones. If we do, we should be using the PATCH '/teams/:team_id/members', which feels better to me.

2017-10-23 22:30 UTC, RasPhilCo commented
@kahlouie @jdxcode `members:set` updated to use `PATCH`

2017-10-23 23:10 UTC, kahlouie commented
yay! 🎉

2017-10-23 23:10 UTC, kahlouie approved these changes

2017-10-24 17:12 UTC, RasPhilCo commented
@kahlouie Cool!

@jdxcode Do you want to take a final look before merging?

2017-10-24 21:35 UTC, jdx approved these changes

2017-10-24 21:59 UTC, merged